apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auto-pod
  namespace: infra-optimize-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easypay
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
