kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-bind
  namespace: infra-optimize-ns
subjects:
  - kind: ServiceAccount
    name: joshua-demebo
    namespace: infra-optimize-ns
roleRef:
      kind: Role
      name: joshua-demebo
      apiGroup: ""
